project_id = "uwsjhtfwxdizxqunplcw"

[functions.verify-admin-password]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.create-midtrans-transaction]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false
